// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SwiftCredentials.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SwiftCredentialsModel
    {
        /// <summary>
        /// Initializes a new instance of the SwiftCredentialsModel class.
        /// </summary>
        public SwiftCredentialsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwiftCredentialsModel class.
        /// </summary>
        public SwiftCredentialsModel(string regulationId, string assetId, string bic = default(string), string accountNumber = default(string), string accountName = default(string), string purposeOfPayment = default(string), string bankAddress = default(string), string companyAddress = default(string), string correspondentAccount = default(string))
        {
            RegulationId = regulationId;
            AssetId = assetId;
            Bic = bic;
            AccountNumber = accountNumber;
            AccountName = accountName;
            PurposeOfPayment = purposeOfPayment;
            BankAddress = bankAddress;
            CompanyAddress = companyAddress;
            CorrespondentAccount = correspondentAccount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bic")]
        public string Bic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountName")]
        public string AccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PurposeOfPayment")]
        public string PurposeOfPayment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankAddress")]
        public string BankAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CompanyAddress")]
        public string CompanyAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CorrespondentAccount")]
        public string CorrespondentAccount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RegulationId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RegulationId");
            }
            if (AssetId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetId");
            }
        }
    }
}
